Repository TeamGalacticraft/Galacticraft, pull requests merged in 2021-03, with the labels that each got.

#86 feat: add Galacticraft 4 music as discs
  src/main/java/com/hrznstudio/galacticraft/Constants.java
  src/main/java/com/hrznstudio/galacticraft/items/GalacticraftItems.java
  src/main/java/com/hrznstudio/galacticraft/sounds/GalacticraftSounds.java
  src/main/resources/assets/galacticraft-rewoven/lang/en_us.json
  src/main/resources/assets/galacticraft-rewoven/models/item/legacy_music_disc_mars.json
  src/main/resources/assets/galacticraft-rewoven/models/item/legacy_music_disc_minmas.json
  src/main/resources/assets/galacticraft-rewoven/models/item/legacy_music_disc_orbit.json
  src/main/resources/assets/galacticraft-rewoven/models/item/legacy_music_disc_spacerace.json
  src/main/resources/assets/galacticraft-rewoven/sounds.json
  src/main/resources/assets/galacticraft-rewoven/sounds/music/legacy/mars.ogg
  src/main/resources/assets/galacticraft-rewoven/sounds/music/legacy/mimas.ogg
  src/main/resources/assets/galacticraft-rewoven/sounds/music/legacy/orbit.ogg
  src/main/resources/assets/galacticraft-rewoven/sounds/music/legacy/spacerace.ogg
  src/main/resources/assets/galacticraft-rewoven/textures/item/legacy_music_disc_mars.png
  src/main/resources/assets/galacticraft-rewoven/textures/item/legacy_music_disc_minmas.png
  src/main/resources/assets/galacticraft-rewoven/textures/item/legacy_music_disc_orbit.png
  src/main/resources/assets/galacticraft-rewoven/textures/item/legacy_music_disc_spacerace.png
  src/main/resources/data/minecraft/tags/items/creeper_drops_music_discs.json
  src/main/resources/galacticraft_rewoven.accesswidener
Labels: Feature, Minor, Ready For Review

#93 chore: drop FOML, use myron instead
  build.gradle
  gradle.properties
  src/main/java/com/hrznstudio/galacticraft/GalacticraftClient.java
  src/main/java/com/hrznstudio/galacticraft/block/GalacticraftBlocks.java
  src/main/java/com/hrznstudio/galacticraft/client/render/entity/BubbleEntityRenderer.java
  src/main/java/com/hrznstudio/galacticraft/client/resource/GCResourceReloadListener.java
  src/main/java/com/hrznstudio/galacticraft/util/OxygenTankUtils.java
  src/main/resources/assets/galacticraft-rewoven/models/block/sphere.mtl
  src/main/resources/assets/galacticraft-rewoven/models/misc/sphere.mtl
  src/main/resources/assets/galacticraft-rewoven/models/misc/sphere.obj
Labels: Ready For Review

#90 chore: Kotlin DSL migration
  build.gradle
  build.gradle.kts
  gradle.properties
  settings.gradle
  settings.gradle.kts
Labels: Feedback Wanted, Priority

#94 chore: repo cleanup
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: Minor, Ready to merge

#96 fix: music disc name typo
  src/main/java/com/hrznstudio/galacticraft/Constants.java
  src/main/java/com/hrznstudio/galacticraft/items/GalacticraftItems.java
  src/main/java/com/hrznstudio/galacticraft/sounds/GalacticraftSounds.java
  src/main/resources/assets/galacticraft-rewoven/lang/en_us.json
  src/main/resources/assets/galacticraft-rewoven/models/item/legacy_music_disc_mimas.json
  src/main/resources/assets/galacticraft-rewoven/models/item/legacy_music_disc_minmas.json
  src/main/resources/assets/galacticraft-rewoven/sounds.json
  src/main/resources/assets/galacticraft-rewoven/textures/item/legacy_music_disc_mimas.png
  src/main/resources/data/minecraft/tags/items/creeper_drops_music_discs.json
Labels: Bug, Minor
