Repository TeamGalacticraft/Galacticraft, pull requests merged in 2021-09, with the labels that each got.

#151 chore: issue forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: status: ready for review, priority: low, type: docs

#147 Feat: Port REI 5 to REI 6
  src/main/java/dev/galacticraft/mod/Constant.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/GalacticraftREIClientPlugin.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/category/BaseWidget.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/category/DefaultCompressingCategory.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/category/DefaultFabricationCategory.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/display/DefaultCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/display/DefaultFabricationDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/display/DefaultShapedCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/display/DefaultShapelessCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/transfer/DefaultTransferHandler.java
  src/main/java/dev/galacticraft/mod/compat/rei/server/GalacticraftREIServerPlugin.java
  src/main/java/dev/galacticraft/mod/compat/rei/server/SimpleMachineMenuInfo.java
  src/main/java/dev/galacticraft/mod/recipe/rei/DefaultCompressingCategory.java
  src/main/java/dev/galacticraft/mod/recipe/rei/DefaultFabricationCategory.java
  src/main/java/dev/galacticraft/mod/recipe/rei/DefaultFabricationDisplay.java
  src/main/java/dev/galacticraft/mod/recipe/rei/DefaultShapedCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/recipe/rei/DefaultShapelessCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/recipe/rei/GalacticraftREIPlugin.java
  src/main/resources/fabric.mod.json
Labels: type: feature, status: ready for review, priority: medium

#154 feat: switch to using creds for reposilite repo
  .github/workflows/codeql.yml
  .github/workflows/pr_check.yml
  .github/workflows/publish.yml
  build.gradle.kts
Labels: type: feature, status: ready for review, priority: medium

#155 build: enable publishing to snapshot repo and publish snapshots from main pushes
  .github/workflows/build.yml
  build.gradle.kts
Labels: type: feature, status: ready for review, priority: medium

#157 fix: don't bother setting the executable bit in actions
  .github/workflows/build.yml
  .github/workflows/codeql.yml
  .github/workflows/pr_check.yml
  .github/workflows/publish.yml
Labels: status: ready for review, priority: low, source: repository, type: cleanup

#160 fix: register chunk generators
  src/main/java/dev/galacticraft/mod/Galacticraft.java
Labels: type: bug, status: ready for review, priority: high, source: galacticraft

#159 cleanup: rei
  src/main/java/dev/galacticraft/mod/Constant.java
  src/main/java/dev/galacticraft/mod/block/entity/ElectricCompressorBlockEntity.java
  src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/CircuitFabricatorScreen.java
  src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/ElectricArcFurnaceScreen.java
  src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/ElectricCompressorScreen.java
  src/main/java/dev/galacticraft/mod/client/gui/screen/ingame/ElectricFurnaceScreen.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/GalacticraftREIClientPlugin.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/category/DefaultCompressingCategory.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/category/DefaultFabricationCategory.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/display/DefaultShapedCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/client/transfer/DefaultTransferHandler.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/GalacticraftREIServerPlugin.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/display/DefaultCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/display/DefaultFabricationDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/display/DefaultShapedCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/display/DefaultShapelessCompressingDisplay.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/transfer/info/FabricationMenuInfo.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/transfer/info/SimpleMachineMenuInfo.java
  src/main/java/dev/galacticraft/mod/compat/rei/common/transfer/info/stack/LBASlotAccessor.java
  src/main/java/dev/galacticraft/mod/compat/rei/server/GalacticraftREIServerPlugin.java
  src/main/java/dev/galacticraft/mod/item/GalacticraftItem.java
  src/main/java/dev/galacticraft/mod/item/InfiniteBatteryItem.java
  src/main/java/dev/galacticraft/mod/item/OxygenTankItem.java
  src/main/java/dev/galacticraft/mod/misc/IntPair.java
  src/main/java/dev/galacticraft/mod/screen/CompressorScreenHandler.java
  src/main/java/dev/galacticraft/mod/screen/GalacticraftScreenHandlerType.java
  src/main/java/dev/galacticraft/mod/screen/RecipeMachineScreenHandler.java
  src/main/java/dev/galacticraft/mod/screen/factory/RecipeMachineScreenHandlerFactory.java
  src/main/java/dev/galacticraft/mod/world/gen/surfacebuilder/MultiBlockSurfaceConfig.java
  src/main/resources/fabric.mod.json
Labels: status: ready for review, priority: medium, type: cleanup

#163 Cave Veins render correctly now
  src/main/java/dev/galacticraft/mod/GalacticraftClient.java
Labels: type: bug, status: ready for merge, priority: low, source: galacticraft

#164 fix: use correct texture for arc furnace face
  src/main/resources/assets/galacticraft/models/block/electric_arc_furnace.json
  src/main/resources/assets/galacticraft/textures/block/electric_arc_furnace.png
Labels: type: bug, status: ready for review, priority: low
