Repository TeamGalacticraft/Galacticraft, pull requests merged in 2021-04, with the labels that each got.

#99 feat: add version decoration
  build.gradle.kts
  cloudbuild.yaml
  gradle.properties
Labels: Ready For Review

#106 Fix: add model, glint for infinite oxygen tank
  src/main/java/com/hrznstudio/galacticraft/items/GalacticraftItems.java
  src/main/java/com/hrznstudio/galacticraft/items/InfiniteOxygenTankItem.java
  src/main/resources/assets/galacticraft-rewoven/models/item/infinite_oxygen_tank.json
Labels: priority: low, status: ready for review, type: bug

#107 Chore: update README to reflect new repository URL
  README.md
Labels: priority: low, status: ready for review, type: bug

#108 Chore: fix README part two: electric boogaloo
  README.md
Labels: priority: low, status: ready for merge, type: bug

#115 fix: remove unnecessary redirect, narrow down other one
  src/main/java/dev/galacticraft/mod/client/render/MoonSkyProperties.java
  src/main/java/dev/galacticraft/mod/mixin/BaseFluidMixin.java
  src/main/java/dev/galacticraft/mod/mixin/client/WorldRendererMixin.java
Labels: priority: medium, source: mod conflict, status: ready for review, type: bug

#117 change: moon world generation
  src/main/java/dev/galacticraft/mod/Constant.java
  src/main/java/dev/galacticraft/mod/mixin/BuiltinBiomesAccessor.java
  src/main/java/dev/galacticraft/mod/village/MoonVillagerType.java
  src/main/java/dev/galacticraft/mod/world/biome/GalacticraftBiome.java
  src/main/java/dev/galacticraft/mod/world/biome/layer/MoonBiomeLayer.java
  src/main/java/dev/galacticraft/mod/world/biome/layer/moon/MoonBaseBiomeLayer.java
  src/main/java/dev/galacticraft/mod/world/biome/layer/moon/MoonEdgeBiomeLayer.java
  src/main/java/dev/galacticraft/mod/world/biome/layer/moon/MoonMareBiomeLayer.java
  src/main/java/dev/galacticraft/mod/world/biome/layer/moon/ValleyCrossSamplingLayer.java
  src/main/java/dev/galacticraft/mod/world/biome/source/MoonBiomeSource.java
  src/main/java/dev/galacticraft/mod/world/gen/carver/LunarCaveCarver.java
  src/main/java/dev/galacticraft/mod/world/gen/chunk/MoonChunkGenerator.java
  src/main/resources/data/galacticraft/worldgen/biome/moon_highlands.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_highlands_edge.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_highlands_valley.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_mare.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_mare_rocks.json
  src/main/resources/data/galacticraft/worldgen/configured_surface_builder/moon_highlands_edge.json
  src/main/resources/galacticraft.accesswidener
  src/main/resources/galacticraft.mixins.json
Labels: priority: low, status: ready for review, type: feature
