Repository TeamGalacticraft/Galacticraft, pull requests merged in 2021-11, with the labels that each got.

#192 Fix: cape json loading
  capes.json
  src/main/java/dev/galacticraft/mod/misc/cape/CapesLoader.java
  src/main/java/dev/galacticraft/mod/mixin/client/AbstractClientPlayerEntityMixin.java
  src/main/resources/assets/galacticraft/lang/en_us.json
Labels: type: bug, status: ready for review, priority: low

#194 feat: use new dimension rendering api
  build.gradle.kts
  gradle.properties
  src/main/java/dev/galacticraft/mod/GalacticraftClient.java
  src/main/java/dev/galacticraft/mod/GalacticraftMixinPlugin.java
  src/main/java/dev/galacticraft/mod/client/render/dimension/EmptyCloudRenderer.java
  src/main/java/dev/galacticraft/mod/client/render/dimension/EmptyWeatherRenderer.java
  src/main/java/dev/galacticraft/mod/client/render/dimension/MoonDimensionEffects.java
  src/main/java/dev/galacticraft/mod/client/render/dimension/MoonSkyRenderer.java
  src/main/java/dev/galacticraft/mod/mixin/client/WorldRendererMixin.java
  src/main/java/dev/galacticraft/mod/mixin/client/WorldRendererMoonMixin.java
  src/main/java/dev/galacticraft/mod/structure/GalacticraftStructure.java
  src/main/java/dev/galacticraft/mod/world/biome/layer/MoonBiomeLayer.java
  src/main/java/dev/galacticraft/mod/world/biome/source/MoonBiomeSource.java
  src/main/resources/galacticraft.mixins.json
Labels: type: feature, status: ready for review, priority: low, source: fabric

#199 feat: setup crowdin for translations
  crowdin.yml
  src/main/resources/assets/galacticraft/lang/en_US.json
  src/main/resources/assets/galacticraft/lang/nn_NO.json
  src/main/resources/assets/galacticraft/lang/pl_PL.json
Labels: type: feature, status: ready for review, priority: high

#200 feat: properly setup crowdin
  .github/workflows/crowdin.yml
  crowdin.yml
Labels: type: feature, priority: medium

#201 fix: broken workflow config for crowdin
  .github/workflows/crowdin.yml
Labels: type: bug, status: ready for review, priority: medium

#202 fix: crowdin config fix attempt 2
  .github/workflows/crowdin.yml
Labels: type: bug, status: ready for review, priority: medium
