Repository TeamGalacticraft/Galacticraft, pull requests merged in 2021-02, with the labels that each got.

#77 Feat: Glowstone Lantern, Unlit Lantern
  src/main/java/com/hrznstudio/galacticraft/Constants.java
  src/main/java/com/hrznstudio/galacticraft/GalacticraftClient.java
  src/main/java/com/hrznstudio/galacticraft/block/GalacticraftBlocks.java
  src/main/java/com/hrznstudio/galacticraft/block/environment/GlowstoneLanternBlock.java
  src/main/java/com/hrznstudio/galacticraft/block/environment/UnlitLanternBlock.java
  src/main/java/com/hrznstudio/galacticraft/mixin/LanternBlockMixin.java
  src/main/resources/assets/galacticraft-rewoven/blockstates/glowstone_lantern.json
  src/main/resources/assets/galacticraft-rewoven/blockstates/unlit_lantern.json
  src/main/resources/assets/galacticraft-rewoven/lang/en_us.json
  src/main/resources/assets/galacticraft-rewoven/models/block/glowstone_lantern.json
  src/main/resources/assets/galacticraft-rewoven/models/block/glowstone_lantern_hanging.json
  src/main/resources/assets/galacticraft-rewoven/models/block/unlit_lantern.json
  src/main/resources/assets/galacticraft-rewoven/models/block/unlit_lantern_hanging.json
  src/main/resources/assets/galacticraft-rewoven/models/item/glowstone_lantern.json
  src/main/resources/assets/galacticraft-rewoven/models/item/unlit_lantern.json
  src/main/resources/assets/galacticraft-rewoven/textures/block/glowstone_lantern.png
  src/main/resources/assets/galacticraft-rewoven/textures/block/glowstone_lantern.png.mcmeta
  src/main/resources/assets/galacticraft-rewoven/textures/block/unlit_lantern.png
  src/main/resources/assets/galacticraft-rewoven/textures/block/unlit_lantern.png.mcmeta
  src/main/resources/assets/galacticraft-rewoven/textures/item/glowstone_lantern.png
  src/main/resources/assets/galacticraft-rewoven/textures/item/unlit_lantern.png
  src/main/resources/data/galacticraft-rewoven/recipes/glowstone_lantern.json
  src/main/resources/galacticraft-rewoven.mixins.json
Labels: Feature, Ready For Review

#78 fix: don't load client-only classes on the server
  src/main/java/com/hrznstudio/galacticraft/GalacticraftClient.java
  src/main/java/com/hrznstudio/galacticraft/api/block/ConfigurableMachineBlock.java
  src/main/java/com/hrznstudio/galacticraft/particle/GalacticraftParticles.java
Labels: Bug, Ready For Review

#80 Feat: Additional Commands
  src/main/java/com/hrznstudio/galacticraft/server/command/GalacticraftCommands.java
  src/main/resources/assets/galacticraft-rewoven/lang/en_us.json
Labels: Feature, Ready For Review

#82 chore: update to minecraft 1.16.5
  build.gradle
  build.sh
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/com/hrznstudio/galacticraft/block/GalacticraftBlocks.java
  src/main/java/com/hrznstudio/galacticraft/block/decoration/MoonCheeseBlock.java
  src/main/resources/galacticraft_rewoven.accesswidener
Labels: Minor, Ready For Review

#83 feat: networked blocks v3
  src/main/java/com/hrznstudio/galacticraft/api/block/FluidPipe.java
  src/main/java/com/hrznstudio/galacticraft/api/block/WireBlock.java
  src/main/java/com/hrznstudio/galacticraft/api/block/entity/ConfigurableMachineBlockEntity.java
  src/main/java/com/hrznstudio/galacticraft/api/block/entity/WireBlockEntity.java
  src/main/java/com/hrznstudio/galacticraft/api/pipe/Pipe.java
  src/main/java/com/hrznstudio/galacticraft/api/pipe/PipeNetwork.java
  src/main/java/com/hrznstudio/galacticraft/api/pipe/impl/PipeNetworkImpl.java
  src/main/java/com/hrznstudio/galacticraft/api/wire/Wire.java
  src/main/java/com/hrznstudio/galacticraft/api/wire/impl/WireNetworkImpl.java
  src/main/java/com/hrznstudio/galacticraft/block/entity/CircuitFabricatorBlockEntity.java
  src/main/java/com/hrznstudio/galacticraft/block/entity/CompressorBlockEntity.java
  src/main/java/com/hrznstudio/galacticraft/block/entity/ElectricCompressorBlockEntity.java
  src/main/java/com/hrznstudio/galacticraft/block/special/fluidpipe/FluidPipeBlockEntity.java
  src/main/java/com/hrznstudio/galacticraft/block/special/fluidpipe/GlassFluidPipeBlock.java
  src/main/java/com/hrznstudio/galacticraft/client/render/block/entity/FluidPipeBlockEntityRenderer.java
  src/main/java/com/hrznstudio/galacticraft/component/GalacticraftComponents.java
  src/main/resources/data/galacticraft-rewoven/loot_tables/blocks/oxygen_pipe.json
  src/main/resources/data/galacticraft-rewoven/recipes/oxygen_gear.json
  src/main/resources/data/galacticraft-rewoven/recipes/oxygen_pipe.json
  src/main/resources/data/galacticraft-rewoven/recipes/pipe_walkway.json
  src/main/resources/data/galacticraft-rewoven/recipes/pipe_walkway_shapeless.json
Labels: Bug, Ready For Review

#85 feat: add auto licenser
  .github/workflows/gradle.yml
  LICENSE_HEADER.txt
  build.gradle
  cloudbuild.yaml
  src/main/java/com/hrznstudio/galacticraft/entity/EvolvedSkeletonEntity.java
Labels: Feature, Ready For Review

#87 chore: update modmenu api impl
  src/main/java/com/hrznstudio/galacticraft/hooks/ModMenuApiImpl.java
Labels: Minor
