Repository TeamGalacticraft/Galacticraft, pull requests merged in 2021-05, with the labels that each got.

#119 feat: moon craters
  src/main/java/dev/galacticraft/mod/world/gen/carver/CraterCarver.java
  src/main/java/dev/galacticraft/mod/world/gen/carver/GalacticraftCarver.java
  src/main/java/dev/galacticraft/mod/world/gen/chunk/MoonChunkGenerator.java
  src/main/resources/data/galacticraft/worldgen/biome/moon_highlands.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_highlands_edge.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_mare.json
  src/main/resources/data/galacticraft/worldgen/biome/moon_mare_edge.json
  src/main/resources/data/galacticraft/worldgen/configured_carver/moon_crater.json
Labels: priority: medium, status: ready for review, type: feature

#112 Feat: add alpha loading screen warning
  src/main/java/dev/galacticraft/mod/Constant.java
  src/main/java/dev/galacticraft/mod/api/config/Config.java
  src/main/java/dev/galacticraft/mod/config/ConfigImpl.java
  src/main/java/dev/galacticraft/mod/config/ConfigManagerImpl.java
  src/main/java/dev/galacticraft/mod/mixin/client/AlphaWarningTitleScreenMixin.java
  src/main/resources/assets/galacticraft/lang/en_us.json
  src/main/resources/assets/galacticraft/textures/gui/alpha_warning.png
  src/main/resources/galacticraft.mixins.json
Labels: priority: low, status: ready for review, type: feature

#104 feat: rewrite capes system
  src/main/java/dev/galacticraft/mod/GalacticraftClient.java
  src/main/java/dev/galacticraft/mod/api/cape/CapeListener.java
  src/main/java/dev/galacticraft/mod/api/cape/model/CapeModel.java
  src/main/java/dev/galacticraft/mod/api/cape/model/CapePlayer.java
  src/main/java/dev/galacticraft/mod/misc/cape/CapesLoader.java
  src/main/java/dev/galacticraft/mod/misc/cape/JsonCape.java
  src/main/java/dev/galacticraft/mod/mixin/client/AbstractClientPlayerEntityMixin.java
Labels: priority: low, status: ready for review, type: feature

#122 feat: add pr spec to contributing guidelines
  .github/CONTRIBUTING.md
Labels: priority: low, status: ready for merge

#123 fix: logger not replacing parameters
  src/main/java/dev/galacticraft/mod/log/GalacticraftPrependingMessageFactory.java
Labels: priority: low, status: ready for review, type: bug

#126 fix: circuit fabricator recipes
  src/main/resources/data/galacticraft/recipes/fabrication_advanced_wafer.json
  src/main/resources/data/galacticraft/recipes/fabrication_basic_wafer.json
  src/main/resources/data/galacticraft/recipes/fabrication_blue_solar_wafer.json
  src/main/resources/data/galacticraft/recipes/fabrication_solar_array_wafer.json
Labels: priority: medium, status: ready for review, type: bug

#125 feat: improve Github actions
  .github/workflows/build.yml
  .github/workflows/pr_check.yml
  .github/workflows/publish.yml
Labels: priority: medium, status: ready for review, type: feature

#127 chore(docs): improve readme
  README.md
Labels: priority: low, status: ready for review, type: docs

#129 fix: run actions when PRs are opened
  .github/workflows/pr_check.yml
Labels: priority: low, status: ready for review, type: bug

#130 chore: GitHub improvements
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/feature.md
  .github/workflows/build.yml
  .github/workflows/pr_check.yml
Labels: priority: low, status: ready for review, type: feature
